"""shuttle_contributions: per-court attribution

Revision ID: 888fecba73f9
Revises: dcf0caf95930
Create Date: 2026-04-29 22:51:30.999763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888fecba73f9'
down_revision: Union[str, Sequence[str], None] = 'dcf0caf95930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Existing shuttle_contributions rows used the legacy "per-owner total" model
    which is incompatible with the new per-court attribution. Wipe them before
    adding the NOT NULL court_id column.
    """
    op.execute("DELETE FROM shuttle_contributions")
    with op.batch_alter_table('shuttle_contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('court_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_session_owner'), type_='unique')
        batch_op.create_unique_constraint('uq_session_court_owner', ['session_id', 'court_id', 'owner_player_id'])
        batch_op.create_foreign_key('fk_shuttle_court', 'courts', ['court_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shuttle_contributions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_session_court_owner', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_session_owner'), ['session_id', 'owner_player_id'])
        batch_op.drop_column('court_id')

    # ### end Alembic commands ###
